import { IPage } from './Page';
import { ISection } from './Section';
import { IColumn } from './Column';
import { IText } from './Text';
import { IImage } from './Image';
import { IGroup } from './Group';
import { IButton } from './Button';
import { IDivider } from './Divider';
import { IWrapper } from './Wrapper';
import { ISpacer } from './Spacer';
import { ICarousel } from './Carousel';
import { IHero } from './Hero';
import { INavbar } from './Navbar';
import { ISocial } from './Social';
import { IRaw } from './Raw';
import { ITemplate } from './Template';
import { IAccordion } from './Accordion';
import { IAccordionElement } from './AccordionElement';
import { IAccordionTitle } from './AccordionTitle';
import { IAccordionText } from './AccordionText';
import { ITable } from './Table';
export declare const standardBlocks: {
    Page: import("../..").IBlock<IPage>;
    Section: import("../..").IBlock<ISection>;
    Column: import("../..").IBlock<IColumn>;
    Text: import("../..").IBlock<IText>;
    Image: import("../..").IBlock<IImage>;
    Group: import("../..").IBlock<IGroup>;
    Button: import("../..").IBlock<IButton>;
    Divider: import("../..").IBlock<IDivider>;
    Wrapper: import("../..").IBlock<IWrapper>;
    Spacer: import("../..").IBlock<ISpacer>;
    Raw: import("../..").IBlock<IRaw>;
    Carousel: import("../..").IBlock<ICarousel>;
    Hero: import("../..").IBlock<IHero>;
    Navbar: import("../..").IBlock<INavbar>;
    Social: import("../..").IBlock<ISocial>;
    Template: import("../..").IBlock<ITemplate>;
    Accordion: import("../..").IBlock<IAccordion>;
    AccordionElement: import("../..").IBlock<IAccordionElement>;
    AccordionTitle: import("../..").IBlock<import("../..").IBlockData<any, any>>;
    AccordionText: import("../..").IBlock<import("../..").IBlockData<any, any>>;
    Table: import("../..").IBlock<ITable>;
};
export type { IPage, ISection, IWrapper, IColumn, IGroup, IText, ITable, IImage, IButton, IDivider, ISpacer, ICarousel, IHero, ISocial, INavbar, IRaw, IAccordion, IAccordionElement, IAccordionTitle, IAccordionText, ITemplate, };
